using System;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Lox.Analyzers;

[Generator(LanguageNames.CSharp)]
public sealed class LoxAstGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var definitions = context.AdditionalTextsProvider
            .Where(static text => Path.GetFileName(text.Path).Equals("Expr.txt", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, token) => ExtractDefinitions(text.GetText(token)))
            .Collect();

        context.RegisterSourceOutput(definitions, RenderOutput);
    }

    private static EquatableImmutableArray<AstObject> ExtractDefinitions(SourceText? text)
    {
        if (text is null)
        {
            return new EquatableImmutableArray<AstObject>
            {
                Items = [],
            };
        }

        var builder = ImmutableArray.CreateBuilder<AstObject>();

        foreach (var line in text.Lines)
        {
            var span = line.ToString().AsSpan().Trim();
            if (span.IsEmpty) continue;

            var (name, memberSpan) = span.SplitAround(':');

            ImmutableArray<(string, string)> members;
            if (memberSpan.IsEmpty)
            {
                members = ImmutableArray<(string, string)>.Empty;
            }
            else
            {
                var memberBuilder = ImmutableArray.CreateBuilder<(string, string)>();
                while (!memberSpan.IsEmpty)
                {
                    (var member, memberSpan) = memberSpan.SplitAround(',');
                    var (memberType, memberName) = member.Trim().SplitAround(' ');
                    memberBuilder.Add((memberType.Trim().ToString(), TitleCase(memberName.Trim())));
                }

                members = memberBuilder.DrainToImmutable();
            }

            builder.Add(new AstObject(name.Trim().ToString(), new EquatableImmutableArray<(string Type, string Name)>
            {
                Items = members,
            }));
        }

        return new EquatableImmutableArray<AstObject>
        {
            Items = builder.DrainToImmutable(),
        };
    }

    private static void RenderOutput(SourceProductionContext context,
        ImmutableArray<EquatableImmutableArray<AstObject>> types)
    {
        var sb = new IndentingStringBuilder();
        sb
            .AppendLine("// <auto-generated />")
            .AppendLine();
        using (sb.StartBlock("namespace Lox"))
        {
            using (sb.StartBlock("public abstract record Expr"))
            {
                foreach (var outer in types)
                {
                    foreach (var type in outer.Items)
                    {
                        WriteType(sb, type);
                    }
                }
            }
        }

        context.AddSource("Expr.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8, SourceHashAlgorithm.Sha1));
    }

    internal static void WriteType(IndentingStringBuilder sb, AstObject type)
    {
        sb.Append($"public sealed record {type.Name}");
        if (!type.Members.Items.IsEmpty)
        {
            sb.Append("(");
            var first = true;
            foreach (var member in type.Members.Items)
            {
                if (!first)
                {
                    sb.Append(", ");
                }

                sb.Append($"{member.Type} {member.Name}");
                first = false;
            }

            sb.Append(")");
        }

        sb.AppendLine(" : Expr;");
    }

    private static string TitleCase(ReadOnlySpan<char> s)
    {
        return char.ToUpperInvariant(s[0]) + s[1..].ToString();
    }
}

public sealed record AstObject(string Name, EquatableImmutableArray<(string Type, string Name)> Members);
