using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;

namespace Lox.Analyzers.Tests;

public sealed class LoxAstGeneratorTests : CSharpSourceGeneratorTest<LoxAstGenerator, DefaultVerifier>
{
    public LoxAstGeneratorTests()
    {
        ReferenceAssemblies = ReferenceAssemblies.Net.Net100;
    }

    [Fact]
    public async Task BasicScenario()
    {
        await RunTest(
            """
            Binary : Expr left, Token operator, Expr right
            """,
            """
            // <auto-generated />

            namespace Lox
            {
                public abstract record Expr
                {
                    public interface Visitor<out T>
                    {
                        T VisitBinary(Binary expr);
                    }

                    public abstract T Accept<T>(Visitor<T> visitor);

                    public sealed record Binary(Expr Left, Token Operator, Expr Right) : Expr
                    {
                        public override T Accept<T>(Visitor<T> visitor) => visitor.VisitBinary(this);
                    }
                }
            }

            """);
    }

    private async Task RunTest(string input, [StringSyntax("c#")] string expected)
    {
        TestState.AdditionalFiles.Add(("Expr.txt", input));
        TestState.GeneratedSources.Add((typeof(LoxAstGenerator), "Expr.g.cs",
            SourceText.From(expected, Encoding.UTF8, SourceHashAlgorithm.Sha1)));
        CompilerDiagnostics = CompilerDiagnostics.None;
        await RunAsync(TestContext.Current.CancellationToken);
    }
}
